#!/usr/bin/env python
"""Make pip-installed Isaac Sim analyzable by `ty`.

Isaac Sim's modules live in ~600 per-extension dirs that kit only adds to
sys.path at runtime. `omni.*`, `pxr`, `carb` are namespace packages and merge
fine from extra-paths; `isaacsim.*` does NOT, because site-packages/isaacsim has
a real __init__.py that shadows the namespace fragments. We rebuild the merged
isaacsim tree (as kit does to isaacsim.__path__) under ./.lsp and list every ext
root in ty.toml's extra-paths (./.lsp first so the merged isaacsim wins).

Re-run after every `uv sync` (ext version dirs change). Idempotent.
"""

import contextlib
import json
import os
from pathlib import Path
import shutil
import sys

ROOT = Path(__file__).resolve().parent.parent
# Derive site-packages from THIS interpreter's prefix (a sourced ROS PYTHONPATH
# must not decide it). Falls back to a glob under the venv prefix.
cand = list(Path(sys.prefix).glob("lib/python*/site-packages"))
SITE = cand[0] if cand else Path(sys.prefix) / "Lib" / "site-packages"
ISAAC = SITE / "isaacsim"
if not ISAAC.is_dir():
    sys.exit(
        f"isaacsim not found under {SITE} — run inside the venv "
        f"(uv run python scripts/gen_isaac_lsp.py)"
    )

EXT_ROOTS = [
    "exts",
    "extscache",
    "extsDeprecated",
    "kit/exts",
    "kit/extscore",
    "kit/extsPhysics",
]


def ext_dirs():
    """Yield each per-extension directory under ISAAC's known ext roots."""
    for r in EXT_ROOTS:
        base = ISAAC / r
        if base.is_dir():
            for d in sorted(base.iterdir()):
                if d.is_dir():
                    yield d


# --- 1. extraPaths for omni/pxr/carb/etc (namespace pkgs merge natively) ---
TOP = {"omni", "pxr", "carb", "warp", "usdrt", "pip_prebundle"}
extra = []
kernel_py = ISAAC / "kit" / "kernel" / "py"  # carb, omni.kit_app live here
if kernel_py.is_dir():
    extra.append(kernel_py)
for d in ext_dirs():
    try:
        names = {p.name for p in d.iterdir()}
    except OSError:
        continue
    if names & TOP or any(
        n.endswith((".py", ".pyi")) and not n.startswith("_") for n in names
    ):
        extra.append(d)

# --- 2. merged isaacsim/ overlay under ./.lsp (defeats the __init__.py shadow) ---
LSP = ROOT / ".lsp"
if LSP.exists():
    shutil.rmtree(LSP)
dst_isaac = LSP / "isaacsim"
dst_isaac.mkdir(parents=True)
# copy the real top-level files so it stays a regular package (matches runtime types)
for f in ISAAC.iterdir():
    if f.is_file() and f.suffix in {".py", ".pyi"}:
        shutil.copy2(f, dst_isaac / f.name)


def merge(src: Path, dst: Path):
    """Overlay src onto dst the way PEP 420 + kit do.

    Namespace levels (dirs with no __init__) become real dirs and recurse so
    multiple exts can share them; an owned package (has __init__) is symlinked
    whole.
    """
    dst.mkdir(parents=True, exist_ok=True)
    for child in src.iterdir():
        target = dst / child.name
        is_pkg = child.is_dir() and (
            (child / "__init__.py").exists() or (child / "__init__.pyi").exists()
        )
        if child.is_dir() and not is_pkg:
            merge(child, target)  # namespace level: keep descending
        elif not target.exists():
            with contextlib.suppress(OSError):
                target.symlink_to(child)  # owned package or module file


count = 0
ext_list = list(ext_dirs())
for d in ext_list:
    inner = d / "isaacsim"
    if inner.is_dir():
        merge(inner, dst_isaac)
        count += 1

# --- 2b. inject hand-written stubs next to compiled .so bindings. A stub in a
# separate path can't help when the binding lives in a *regular* package (i.e. one
# with an __init__): the package shadows it. So copy each typings/*.pyi beside the
# real module in its owning ext dir. Idempotent; redone each run. Currently a no-op
# (no checked-in stubs); kept for any future compiled binding ty can't introspect. ---
TYPINGS = ROOT / "typings"
injected = 0
if TYPINGS.is_dir():
    for stub in TYPINGS.rglob("*.pyi"):
        relmod = stub.parent.relative_to(TYPINGS)  # e.g. omni/some/compiled_ext
        for d in ext_list:
            dest_dir = d / relmod
            if dest_dir.is_dir():
                dest = dest_dir / stub.name
                if not dest.exists():
                    try:
                        shutil.copy2(stub, dest)
                        injected += 1
                    except OSError:
                        pass
                break


# --- 3. write ty.toml (.lsp first so the merged isaacsim wins; typings holds
#        hand-written stubs for compiled .so bindings ty can't introspect) ---
def rel(p: Path):
    """Return p as a path relative to ROOT (for ty.toml extra-paths)."""
    return os.path.relpath(p, ROOT)


paths = [".lsp", "typings", "src"] + [rel(p) for p in extra]
lines = [
    "# GENERATED by scripts/gen_isaac_lsp.py — re-run after every `uv sync`.",
    "# Isaac Sim ships its modules across ~600 per-extension dirs that kit only",
    "# adds to sys.path at runtime; these extra-paths give ty the same view.",
    "",
    "[environment]",
    'python = ".venv"',
    'python-version = "3.12"',
    "extra-paths = [",
    *[f"    {json.dumps(p)}," for p in paths],
    "]",
    "",
    "[src]",
    'include = ["src/isaacrace"]',
    "",
    "[rules]",
    # the only import ty can't satisfy is compiled .so bindings without a .pyi
    'unresolved-import = "warn"',
]
(ROOT / "ty.toml").write_text("\n".join(lines) + "\n")
print(f"merged {count} isaacsim ext roots into .lsp/isaacsim")
print(f"injected {injected} stub(s) beside compiled bindings")
print(f"wrote ty.toml with {len(paths)} extra-paths")
